[package]
name = "euv-example"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """An example application demonstrating the euv UI framework with reactive signals, custom components, and WebAssembly."""
keywords = ["cross-platform"]
categories = ["network-programming", "web-programming"]
publish = false
exclude.workspace = true
[dependencies]
euv = { workspace = true }
euv-ui = { workspace = true }
euv-engine = { workspace = true }


serde = { workspace = true }
qrcode = { workspace = true }
serde_json = { workspace = true }
lombok-macros = { workspace = true }
compare_version = { workspace = true }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
[build-dependencies]
chrono = { workspace = true }

[dev-dependencies]
euv-macros = { workspace = true }

[lib]
crate-type = ["cdylib"]
