[package]
name = "euv-engine"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """A high-performance 2D game engine built on the euv framework, featuring ECS, fixed-timestep game loop, canvas rendering, physics, collision detection, sprite animation, and audio."""
keywords = ["cross-platform", "game-engine", "2d", "wasm"]
categories = ["web-programming", "game-engines"]
exclude.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
euv = { workspace = true }

js-sys = { workspace = true }
lombok-macros = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }

