[package]
name = "euv-cli"
version = "0.18.64"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """The official CLI tool for the euv UI framework, providing dev/release profiles with run/build modes, hot reload, and wasm-pack integration."""
keywords = ["cross-platform"]
repository = "https://github.com/euv-dev/euv.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github", "logs", "img", "**/*.log"]

[[bin]]
name = "euv"
path = "src/main.rs"

[dependencies]
log = { workspace = true }
syn = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
ignore = { workspace = true }
notify = { workspace = true }
qrcode = { workspace = true }
if-addrs = { workspace = true }
hyperlane = { workspace = true }
serde_json = { workspace = true }
proc-macro2 = { workspace = true }
color-output = { workspace = true }
hyperlane-cli = { workspace = true }
lombok-macros = { workspace = true }
