[package]
name = "euv-cli"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """The official CLI tool for the euv UI framework, providing dev/release profiles with run/build modes, hot reload, and wasm-pack integration."""
keywords = ["cross-platform"]
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[[bin]]
name = "euv"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
color-output = { workspace = true }
hyperlane = { workspace = true }
hyperlane-cli = { workspace = true }
if-addrs = { workspace = true }
ignore = { workspace = true }
log = { workspace = true }
lombok-macros = { workspace = true }
notify = { workspace = true }
proc-macro2 = { workspace = true }
qrcode = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
tokio = { workspace = true }

