[package]
name = "euv-core"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """A declarative, cross-platform UI framework for Rust with virtual DOM, reactive signals, and HTML macros for WebAssembly."""
keywords = ["cross-platform"]
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
js-sys = { workspace = true }
web-sys = { workspace = true }
wasm-bindgen = { workspace = true }
lombok-macros = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-test = { workspace = true }
