[package]
name = "euv-core"
version = "0.20.1"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A declarative, cross-platform UI framework for Rust with virtual DOM, reactive signals, and HTML macros for WebAssembly."""
keywords = ["cross-platform"]
repository = "https://github.com/euv-dev/euv.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github", "logs", "img", "**/*.log"]

[lib]
crate-type = ["rlib"]

[dependencies]
js-sys = { workspace = true }
web-sys = { workspace = true }
wasm-bindgen = { workspace = true }
lombok-macros = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-test = { workspace = true }
